name: movie_db
description: A movie ticket booking app.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^4.0.6
  provider: ^6.0.3
  google_fonts: ^4.0.4
  cupertino_icons: ^1.0.5
  flutter_search_bar: ^3.0.0-dev.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/logo.png
  
flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/